# Exploratory Data Analysis and Insights on the Automobile Dataset Using Pandas

### Beginner-to-Intermediate Pandas Practice Notebook

This notebook is designed for students who are learning how to clean and explore mixed numerical and categorical data using **Pandas**.

The exercises begin with basic DataFrame operations and gradually introduce:

- Loading a CSV file with custom missing-value markers
- Inspecting rows, columns, and data types
- Finding and handling missing values
- Selecting, filtering, and sorting records
- Exploring vehicle categories
- Calculating descriptive statistics
- Grouping and aggregating data
- Creating derived columns
- Examining correlations
- Creating basic visualizations
- Exporting cleaned data

## About the Dataset

The **Automobile.csv** dataset contains information about **205 automobiles** from the 1985 model year.

It contains **26 columns** describing vehicle specifications, fuel economy, insurance risk, and price.

### Main Column Groups

| Group | Example columns | Description |
|---|---|---|
| Vehicle identity | `make`, `fuel_type`, `body_style` | Manufacturer and vehicle categories |
| Size and weight | `wheel_base`, `length`, `width`, `curb_weight` | Physical measurements and vehicle weight |
| Engine | `engine_type`, `num_cylinders`, `engine_size`, `horsepower` | Engine design and performance information |
| Fuel economy | `city_mpg`, `highway_mpg` | City and highway fuel efficiency |
| Cost and risk | `price`, `symboling`, `normalized_losses` | Vehicle price and insurance-risk information |

### Important Observation

The original dataset uses a question mark (`?`) to represent missing information. When loading the CSV, use the `na_values` parameter so Pandas treats these markers as missing values.

The original hyphenated field names were converted to lowercase names with underscores to make them easier to use in Python.

**Source:** [UCI Machine Learning Repository](https://archive.ics.uci.edu/dataset/10/automobile)  
**License:** CC BY 4.0

## Learning Goal

By completing this assignment, you will practice a complete beginner-to-intermediate data-cleaning and exploration workflow. You will work with missing values, compare vehicle groups, calculate useful derived measures, and summarize the relationships between price, performance, and fuel economy.

## 1. Loading and Understanding the Dataset

### Question 1
Import the Pandas library using the alias `pd` and read **Automobile.csv** into a DataFrame named `df`. Use `na_values='?'` so question marks are treated as missing values.

In [2]:
import pandas as pd
data = "https://raw.githubusercontent.com/hakimyameen/Data-Science-Assignments/main/Assignment%203/Automobile.csv"
df = pd.read_csv(data , na_values = '?')
df

,symboling,normalized_losses,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
201,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
202,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
203,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
204,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

### Question 2
Display the first **5 rows** of the dataset.

In [3]:
df.head()

,symboling,normalized_losses,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0

### Question 3
Display the last **5 rows** of the dataset.

In [12]:
df.tail()

,symboling,normalized_losses,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
200,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
201,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
202,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
203,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
204,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

### Question 4
Find the total number of **rows and columns** in the dataset.

In [15]:
df.shape

(205, 26)

### Question 5
Display all the **column names** in the dataset.

In [16]:
df.columns

Index(['symboling', 'normalized_losses', 'make', 'fuel_type', 'aspiration',
       'num_doors', 'body_style', 'drive_wheels', 'engine_location',
       'wheel_base', 'length', 'width', 'height', 'curb_weight', 'engine_type',
       'num_cylinders', 'engine_size', 'fuel_system', 'bore', 'stroke',
       'compression_ratio', 'horsepower', 'peak_rpm', 'city_mpg',
       'highway_mpg', 'price'],
      dtype='str')

### Question 6
Display the **data type of each column**.

In [2]:
df.dtypes

symboling              int64
normalized_losses    float64
make                     str
fuel_type                str
aspiration               str
num_doors                str
body_style               str
drive_wheels             str
engine_location          str
wheel_base           float64
length               float64
width                float64
height               float64
curb_weight            int64
engine_type              str
num_cylinders            str
engine_size            int64
fuel_system              str
bore                 float64
stroke               float64
compression_ratio    float64
horsepower           float64
peak_rpm             float64
city_mpg               int64
highway_mpg            int64
price                float64
dtype: object

### Question 7
Display a complete summary of the DataFrame using `info()`.

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized_losses  164 non-null    float64
 2   make               205 non-null    str
 3   fuel_type          205 non-null    str
 4   aspiration         205 non-null    str
 5   num_doors          203 non-null    str
 6   body_style         205 non-null    str
 7   drive_wheels       205 non-null    str
 8   engine_location    205 non-null    str
 9   wheel_base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb_weight        205 non-null    int64
 14  engine_type        205 non-null    str
 15  num_cylinders      205 non-null    str
 16  engine_size        205 non-null    int64
 17  fuel_system        205 non-null    str
 18  bore               201 non-null    float64
 19  stroke             201 non-null    float64
 20  compression_ratio  205 non-null    float64
 21  horsepower         203 non-null    float64
 22  peak_rpm           203 non-null    float64
 23  city_mpg           205 non-null    int64
 24  highway_mpg        205 non-null    int64
 25  price              201 non-null    float64
dtypes: float64(11), int64(5), str(10)
memory usage: 41.8 KB

## 2. Checking and Handling Missing Values

### Question 8
Display the number of **missing values in each column**.

In [4]:
df.isna().sum()

symboling             0
normalized_losses    41
make                  0
fuel_type             0
aspiration            0
num_doors             2
body_style            0
drive_wheels          0
engine_location       0
wheel_base            0
length                0
width                 0
height                0
curb_weight           0
engine_type           0
num_cylinders         0
engine_size           0
fuel_system           0
bore                  4
stroke                4
compression_ratio     0
horsepower            2
peak_rpm              2
city_mpg              0
highway_mpg           0
price                 4
dtype: int64

### Question 9
Display only the columns that contain **at least one missing value**.

In [3]:
df.loc[: , df.isnull().any()]

     normalized_losses num_doors  bore  stroke  horsepower  peak_rpm    price
0                  NaN       two  3.47    2.68       111.0    5000.0  13495.0
1                  NaN       two  3.47    2.68       111.0    5000.0  16500.0
2                  NaN       two  2.68    3.47       154.0    5000.0  16500.0
3                164.0      four  3.19    3.40       102.0    5500.0  13950.0
4                164.0      four  3.19    3.40       115.0    5500.0  17450.0
..                 ...       ...   ...     ...         ...       ...      ...
200               95.0      four  3.78    3.15       114.0    5400.0  16845.0
201               95.0      four  3.78    3.15       160.0    5300.0  19045.0
202               95.0      four  3.58    2.87       134.0    5500.0  21485.0
203               95.0      four  3.01    3.40       106.0    4800.0  22470.0
204               95.0      four  3.78    3.15       114.0    5400.0  22625.0

[205 rows x 7 columns]

### Question 10
Calculate the **total number of missing values** in the entire DataFrame.

In [27]:
df.isna().sum().sum()

np.int64(59)

### Question 11
Display all rows where the **price** is missing.

In [34]:
df[df['price'].isna()]

,symboling,normalized_losses,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
9,0,NaN,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160.0,5500.0,16,22,NaN
44,1,NaN,isuzu,gas,std,two,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.6,70.0,5400.0,38,43,NaN
45,0,NaN,isuzu,gas,std,four,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.6,70.0,5400.0,38,43,NaN
129,1,NaN,porsche,gas,std,two,hatchback,rwd,front,98.4,...,203,mpfi,3.94,3.11,10.0,288.0,5750.0,17,28,NaN

### Question 12
Create a DataFrame named `df_clean` by removing rows with missing values in `price` or `horsepower`. Display its shape.

In [5]:
df_clean = df.dropna(subset= ['price', 'horsepower'])
df_clean.shape

(199, 26)

## 3. Selecting Rows and Columns

### Question 13
Select and display only the **make** column from `df_clean`.

In [40]:
df_clean['make']

0      alfa-romero
1      alfa-romero
2      alfa-romero
3             audi
4             audi
          ...
200          volvo
201          volvo
202          volvo
203          volvo
204          volvo
Name: make, Length: 199, dtype: str

### Question 14
Select and display the **make, body_style, horsepower, city_mpg, and price** columns.

In [43]:
df_clean.loc[:,['make', 'body_style','horsepower','city_mpg','price']]

            make   body_style  horsepower  city_mpg    price
0    alfa-romero  convertible       111.0        21  13495.0
1    alfa-romero  convertible       111.0        21  16500.0
2    alfa-romero    hatchback       154.0        19  16500.0
3           audi        sedan       102.0        24  13950.0
4           audi        sedan       115.0        18  17450.0
..           ...          ...         ...       ...      ...
200        volvo        sedan       114.0        23  16845.0
201        volvo        sedan       160.0        19  19045.0
202        volvo        sedan       134.0        18  21485.0
203        volvo        sedan       106.0        26  22470.0
204        volvo        sedan       114.0        19  22625.0

[199 rows x 5 columns]

### Question 15
Using `iloc`, display the first **5 rows and first 6 columns** of `df_clean`.

In [44]:
df_clean.iloc[:5 , :6]

   symboling  normalized_losses         make fuel_type aspiration num_doors
0          3                NaN  alfa-romero       gas        std       two
1          3                NaN  alfa-romero       gas        std       two
2          1                NaN  alfa-romero       gas        std       two
3          2              164.0         audi       gas        std      four
4          2              164.0         audi       gas        std      four

### Question 16
Using `loc`, display rows **10 to 15** for the columns **make, engine_size, horsepower, and price**.

In [47]:
df_clean.loc[10:15 , ['make','engine_size','horsepower', 'price']]

   make  engine_size  horsepower    price
10  bmw          108       101.0  16430.0
11  bmw          108       101.0  16925.0
12  bmw          164       121.0  20970.0
13  bmw          164       121.0  21105.0
14  bmw          164       121.0  24565.0
15  bmw          209       182.0  30760.0

## 4. Exploring Categories and Descriptive Statistics

### Question 17
Display all the **unique automobile manufacturers** in the dataset.

In [58]:
df_clean['make'].unique()

<StringArray>
[  'alfa-romero',          'audi',           'bmw',     'chevrolet',
         'dodge',         'honda',         'isuzu',        'jaguar',
         'mazda', 'mercedes-benz',       'mercury',    'mitsubishi',
        'nissan',        'peugot',      'plymouth',       'porsche',
          'saab',        'subaru',        'toyota',    'volkswagen',
         'volvo']
Length: 21, dtype: str

### Question 18
Count the number of automobiles produced by each manufacturer using `value_counts()`.

In [53]:
df_clean['make'].value_counts()

make
toyota           32
nissan           18
mazda            17
honda            13
mitsubishi       13
subaru           12
volkswagen       12
peugot           11
volvo            11
dodge             9
bmw               8
mercedes-benz     8
plymouth          7
audi              6
saab              6
porsche           4
alfa-romero       3
chevrolet         3
jaguar            3
isuzu             2
mercury           1
Name: count, dtype: int64

### Question 19
Display all unique **body styles** and count the number of automobiles in each style.

In [59]:
df_clean['body_style'].unique()
df_clean['body_style'].value_counts()

body_style
sedan          94
hatchback      67
wagon          24
hardtop         8
convertible     6
Name: count, dtype: int64

### Question 20
Count the values in the **fuel_type** and **aspiration** columns.

In [7]:
df_clean['fuel_type'].value_counts()
df_clean['aspiration'].value_counts()

aspiration
std      163
turbo     36
Name: count, dtype: int64

### Question 21
Display descriptive statistics for the numeric columns in `df_clean` using `describe()`.

In [61]:
df_clean.describe()

,symboling,normalized_losses,wheel_base,length,width,height,curb_weight,engine_size,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
count,199.000000,164.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000,195.000000,195.000000,199.000000,199.000000,199.000000,199.000000,199.000000,199.000000
mean,0.839196,122.000000,98.824121,174.151256,65.882412,53.775879,2556.030151,126.824121,3.329385,3.250308,10.178995,103.396985,5117.587940,25.201005,30.683417,13243.432161
std,1.257009,35.442168,6.090838,12.371905,2.110996,2.447039,519.855544,41.752932,0.271866,0.314115,4.022424,37.553843,480.521824,6.451826,6.849410,7978.707609
min,-2.000000,65.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,0.000000,94.000000,94.500000,166.550000,64.100000,52.000000,2157.000000,97.500000,3.150000,3.110000,8.550000,70.000000,4800.000000,19.000000,25.000000,7775.000000
50%,1.000000,115.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,119.000000,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10345.000000
75%,2.000000,150.000000,102.400000,183.500000,66.700000,55.550000,2930.500000,143.000000,3.590000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16501.500000
max,3.000000,256.000000,120.900000,208.100000,72.000000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,262.000000,6600.000000,49.000000,54.000000,45400.000000

### Question 22
Calculate the **mean price**, **maximum horsepower**, and **minimum city fuel economy**.

In [7]:
df_clean['price'].mean()
df_clean['horsepower'].max()
df_clean['highway_mpg'].min()

np.int64(16)

## 5. Filtering and Sorting

### Question 23
Display all automobiles whose **price is greater than 20,000**.

### Question 24
Display only automobiles manufactured by **Toyota**.

### Question 25
Display all **sedans** with **city_mpg greater than 25**.

### Question 26
Using `query()`, display automobiles whose **horsepower is greater than 120** and **price is less than 20,000**.

### Question 27
Sort `df_clean` by **price in descending order** and display the first 10 rows.

### Question 28
Display the **5 automobiles with the highest highway_mpg**.

## 6. Grouping and Aggregation

### Question 29
Calculate the **average price for each body style**.

### Question 30
Calculate the **average city_mpg and highway_mpg for each fuel type**.

### Question 31
For each drive-wheel category, calculate the **minimum, maximum, and mean price** using `agg()`.

### Question 32
Create a frequency table showing the number of automobiles for each **body_style and fuel_type** using `pd.crosstab()`.

### Question 33
Determine which manufacturer has the **highest average horsepower** among manufacturers with at least 3 automobiles in `df_clean`.

## 7. Creating and Modifying Columns

### Question 34
Create a new column named **price_category** using `apply()` with a `lambda` function. Store `Expensive` when `price` is greater than or equal to 20,000; otherwise store `Affordable`.

### Question 35
Create a new column named **mpg_difference** by subtracting `city_mpg` from `highway_mpg`.

### Question 36
Create a new column named **power_to_weight** by dividing `horsepower` by `curb_weight`.

## 8. Correlation, Visualization, and Export

### Question 37
Create a correlation matrix for **price, horsepower, engine_size, curb_weight, city_mpg, and highway_mpg**.

### Question 38
Create a **histogram** of automobile prices with an appropriate title and axis labels.

### Question 39
Create a **bar chart** showing the average price for each body style.

### Question 40
Save `df_clean` as **Automobile_Cleaned.csv** using `to_csv()` without saving the index.

## End of Practice

Try to solve each question independently before checking any reference material.

The main goal is to become comfortable with cleaning and analyzing a dataset that contains numerical values, categories, and missing information before moving to predictive modeling.