In [2]:
import pandas as pd

path = "https://raw.githubusercontent.com/hakimyameen/Data-Science-Assignments/main/Assignment%201/CO2%20Emissions_Canada.csv"

f = pd.read_csv(path)

print(f.head())

URLError: <urlopen error [Errno 11001] getaddrinfo failed>

In [3]:
# Display the first 5 rows of the dataset.
print(f.head())

    Make       Model Vehicle Class  Engine Size(L)  Cylinders Transmission  \
0  ACURA         ILX       COMPACT             2.0          4          AS5
1  ACURA         ILX       COMPACT             2.4          4           M6
2  ACURA  ILX HYBRID       COMPACT             1.5          4          AV7
3  ACURA     MDX 4WD   SUV - SMALL             3.5          6          AS6
4  ACURA     RDX AWD   SUV - SMALL             3.5          6          AS6

  Fuel Type  Fuel Consumption City (L/100 km)  \
0         Z                               9.9
1         Z                              11.2
2         Z                               6.0
3         Z                              12.7
4         Z                              12.1

   Fuel Consumption Hwy (L/100 km)  Fuel Consumption Comb (L/100 km)  \
0                              6.7                               8.5
1                              7.7                               9.6
2                              5.8                               5.9
3                              9.1                              11.1
4                              8.7                              10.6

   Fuel Consumption Comb (mpg)  CO2 Emissions(g/km)
0                           33                  196
1                           29                  221
2                           48                  136
3                           25                  255
4                           27                  244

In [ ]:
# Question 3
# Display the last 5 rows of the dataset.
print(f.tail())

       Make        Model   Vehicle Class  Engine Size(L)  Cylinders  \
7380  VOLVO  XC40 T5 AWD     SUV - SMALL             2.0          4
7381  VOLVO  XC60 T5 AWD     SUV - SMALL             2.0          4
7382  VOLVO  XC60 T6 AWD     SUV - SMALL             2.0          4
7383  VOLVO  XC90 T5 AWD  SUV - STANDARD             2.0          4
7384  VOLVO  XC90 T6 AWD  SUV - STANDARD             2.0          4

     Transmission Fuel Type  Fuel Consumption City (L/100 km)  \
7380          AS8         Z                              10.7
7381          AS8         Z                              11.2
7382          AS8         Z                              11.7
7383          AS8         Z                              11.2
7384          AS8         Z                              12.2

      Fuel Consumption Hwy (L/100 km)  Fuel Consumption Comb (L/100 km)  \
7380                              7.7                               9.4
7381                              8.3                               9.9
7382                              8.6                              10.3
7383                              8.3                               9.9
7384                              8.7                              10.7

      Fuel Consumption Comb (mpg)  CO2 Emissions(g/km)
7380                           30                  219
7381                           29                  232
7382                           27                  240
7383                           29                  232
7384                           26                  248

In [3]:
# Question 4
    # Find the total number of rows and columns in the dataset.
f.count()

NameError: name 'f' is not defined

In [ ]:
# Question 5
# Display all the column names present in the dataset.
print(f.columns)

Index(['Make', 'Model', 'Vehicle Class', 'Engine Size(L)', 'Cylinders',
       'Transmission', 'Fuel Type', 'Fuel Consumption City (L/100 km)',
       'Fuel Consumption Hwy (L/100 km)', 'Fuel Consumption Comb (L/100 km)',
       'Fuel Consumption Comb (mpg)', 'CO2 Emissions(g/km)'],
      dtype='str')

In [12]:
# Question 6
# Display the data type of each column.
print(f.dtypes)

Make                                    str
Model                                   str
Vehicle Class                           str
Engine Size(L)                      float64
Cylinders                             int64
Transmission                            str
Fuel Type                               str
Fuel Consumption City (L/100 km)    float64
Fuel Consumption Hwy (L/100 km)     float64
Fuel Consumption Comb (L/100 km)    float64
Fuel Consumption Comb (mpg)           int64
CO2 Emissions(g/km)                   int64
dtype: object

In [18]:
# Question 7
# Display a complete summary of the DataFrame using info().
print(f.info())

<class 'pandas.DataFrame'>
RangeIndex: 7385 entries, 0 to 7384
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Make                              7385 non-null   str
 1   Model                             7385 non-null   str
 2   Vehicle Class                     7385 non-null   str
 3   Engine Size(L)                    7385 non-null   float64
 4   Cylinders                         7385 non-null   int64
 5   Transmission                      7385 non-null   str
 6   Fuel Type                         7385 non-null   str
 7   Fuel Consumption City (L/100 km)  7385 non-null   float64
 8   Fuel Consumption Hwy (L/100 km)   7385 non-null   float64
 9   Fuel Consumption Comb (L/100 km)  7385 non-null   float64
 10  Fuel Consumption Comb (mpg)       7385 non-null   int64
 11  CO2 Emissions(g/km)               7385 non-null   int64
dtypes: float64(4), int64(3), str(5)
memory usage: 692.5 KB
None

In [ ]:
# 2. Checking Missing Values
# Question 8
print(f.isnull().sum())

Make                                0
Model                               0
Vehicle Class                       0
Engine Size(L)                      0
Cylinders                           0
Transmission                        0
Fuel Type                           0
Fuel Consumption City (L/100 km)    0
Fuel Consumption Hwy (L/100 km)     0
Fuel Consumption Comb (L/100 km)    0
Fuel Consumption Comb (mpg)         0
CO2 Emissions(g/km)                 0
dtype: int64

In [ ]:
# Question 9
# Check the number of missing values again using isna()
print(f.isna().sum())

Make                                0
Model                               0
Vehicle Class                       0
Engine Size(L)                      0
Cylinders                           0
Transmission                        0
Fuel Type                           0
Fuel Consumption City (L/100 km)    0
Fuel Consumption Hwy (L/100 km)     0
Fuel Consumption Comb (L/100 km)    0
Fuel Consumption Comb (mpg)         0
CO2 Emissions(g/km)                 0
dtype: int64

In [23]:
# Question 10
# Select and display only the Make column.
f['Make']

0       ACURA
1       ACURA
2       ACURA
3       ACURA
4       ACURA
        ...
7380    VOLVO
7381    VOLVO
7382    VOLVO
7383    VOLVO
7384    VOLVO
Name: Make, Length: 7385, dtype: str

In [42]:
# Question 11
# Select and display the Make, Model, and CO2 Emissions(g/km) columns.
f[['Make','Model','CO2 Emissions(g/km)']].head(10)

    Make       Model  CO2 Emissions(g/km)
0  ACURA         ILX                  196
1  ACURA         ILX                  221
2  ACURA  ILX HYBRID                  136
3  ACURA     MDX 4WD                  255
4  ACURA     RDX AWD                  244
5  ACURA         RLX                  230
6  ACURA          TL                  232
7  ACURA      TL AWD                  255
8  ACURA      TL AWD                  267
9  ACURA         TSX                  212

In [ ]:
# Question 12
# Display the first 10 rows using DataFrame slicing.
f.iloc[:10]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
5,ACURA,RLX,MID-SIZE,3.5,6,AS6,Z,11.9,7.7,10.0,28,230
6,ACURA,TL,MID-SIZE,3.5,6,AS6,Z,11.8,8.1,10.1,28,232
7,ACURA,TL AWD,MID-SIZE,3.7,6,AS6,Z,12.8,9.0,11.1,25,255
8,ACURA,TL AWD,MID-SIZE,3.7,6,M6,Z,13.4,9.5,11.6,24,267
9,ACURA,TSX,COMPACT,2.4,4,AS5,Z,10.6,7.5,9.2,31,212

In [44]:
# Question 13
# Using iloc, display the first 5 rows and first 4 columns.
f.iloc[:5,:4]

    Make       Model Vehicle Class  Engine Size(L)
0  ACURA         ILX       COMPACT             2.0
1  ACURA         ILX       COMPACT             2.4
2  ACURA  ILX HYBRID       COMPACT             1.5
3  ACURA     MDX 4WD   SUV - SMALL             3.5
4  ACURA     RDX AWD   SUV - SMALL             3.5

In [ ]:
# Question 14
# Using loc, display rows 0 to 4 for the columns Make, Model, and Cylinders.
f.loc[:4,['Make','Model','CO2 Emissions(g/km)']]

    Make       Model  CO2 Emissions(g/km)
0  ACURA         ILX                  196
1  ACURA         ILX                  221
2  ACURA  ILX HYBRID                  136
3  ACURA     MDX 4WD                  255
4  ACURA     RDX AWD                  244

In [45]:
# 4. Exploring Unique Values
# Question 15
# Display all the unique vehicle manufacturers (Make) in the dataset.
f['Make'].unique()

<StringArray>
[        'ACURA',    'ALFA ROMEO',  'ASTON MARTIN',          'AUDI',
       'BENTLEY',           'BMW',         'BUICK',      'CADILLAC',
     'CHEVROLET',      'CHRYSLER',         'DODGE',          'FIAT',
          'FORD',           'GMC',         'HONDA',       'HYUNDAI',
      'INFINITI',        'JAGUAR',          'JEEP',           'KIA',
   'LAMBORGHINI',    'LAND ROVER',         'LEXUS',       'LINCOLN',
      'MASERATI',         'MAZDA', 'MERCEDES-BENZ',          'MINI',
    'MITSUBISHI',        'NISSAN',       'PORSCHE',           'RAM',
   'ROLLS-ROYCE',         'SCION',         'SMART',           'SRT',
        'SUBARU',        'TOYOTA',    'VOLKSWAGEN',         'VOLVO',
       'GENESIS',       'BUGATTI']
Length: 42, dtype: str

In [58]:
# Question 16
# Find the total number of unique vehicle manufacturers.
f['Make'].nunique()

42

In [ ]:
# Question 17
# Display all unique values from the Fuel Type column.
f['Fuel Type'].unique()

<StringArray>
['Z', 'D', 'X', 'E', 'N']
Length: 5, dtype: str

In [59]:
# Question 18
# Count how many records belong to each Make using value_counts().
f['Make'].value_counts()

Make
FORD             628
CHEVROLET        588
BMW              527
MERCEDES-BENZ    419
PORSCHE          376
TOYOTA           330
GMC              328
AUDI             286
NISSAN           259
JEEP             251
DODGE            246
KIA              231
HONDA            214
HYUNDAI          210
MINI             204
VOLKSWAGEN       197
MAZDA            180
LEXUS            178
JAGUAR           160
CADILLAC         158
SUBARU           140
VOLVO            124
INFINITI         108
BUICK            103
RAM               97
LINCOLN           96
MITSUBISHI        95
CHRYSLER          88
LAND ROVER        85
FIAT              73
ACURA             72
MASERATI          61
ROLLS-ROYCE       50
ASTON MARTIN      47
BENTLEY           46
LAMBORGHINI       41
ALFA ROMEO        30
GENESIS           25
SCION             22
SMART              7
BUGATTI            3
SRT                2
Name: count, dtype: int64

In [ ]:
# Question 19
# Count how many vehicles belong to each Vehicle Class.
f['Vehicle Class'].value_counts()

Vehicle Class
SUV - SMALL                 1217
MID-SIZE                    1133
COMPACT                     1022
SUV - STANDARD               735
FULL-SIZE                    639
SUBCOMPACT                   606
PICKUP TRUCK - STANDARD      538
TWO-SEATER                   460
MINICOMPACT                  326
STATION WAGON - SMALL        252
PICKUP TRUCK - SMALL         159
MINIVAN                       80
SPECIAL PURPOSE VEHICLE       77
VAN - PASSENGER               66
STATION WAGON - MID-SIZE      53
VAN - CARGO                   22
Name: count, dtype: int64

In [ ]:
# 5. Basic Analysis and Filtering
# Question 20
# Find the maximum CO₂ emission value available in the dataset.
f['CO2 Emissions(g/km)'].max()

np.int64(522)

In [72]:
# Question 21
# Display all vehicles whose CO2 Emissions(g/km) are greater than 300.
f[f['CO2 Emissions(g/km)'] > 300]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
13,ASTON MARTIN,DB9,MINICOMPACT,5.9,12,A6,Z,18.0,12.6,15.6,18,359
14,ASTON MARTIN,RAPIDE,SUBCOMPACT,5.9,12,A6,Z,18.0,12.6,15.6,18,359
15,ASTON MARTIN,V8 VANTAGE,TWO-SEATER,4.7,8,AM7,Z,17.4,11.3,14.7,19,338
16,ASTON MARTIN,V8 VANTAGE,TWO-SEATER,4.7,8,M6,Z,18.1,12.2,15.4,18,354
17,ASTON MARTIN,V8 VANTAGE S,TWO-SEATER,4.7,8,AM7,Z,17.4,11.3,14.7,19,338
...,...,...,...,...,...,...,...,...,...,...,...,...
7311,TOYOTA,4Runner 4WD,SUV - STANDARD,4.0,6,AS5,X,14.8,12.5,13.8,20,321
7312,TOYOTA,4Runner 4WD (Part-Time 4WD),SUV - STANDARD,4.0,6,AS5,X,14.8,12.5,13.8,20,321
7348,TOYOTA,Sequoia 4WD,SUV - STANDARD,5.7,8,AS6,X,18.5,13.9,16.4,17,385
7356,TOYOTA,Tundra,PICKUP TRUCK - STANDARD,5.7,8,AS6,X,17.7,13.6,15.9,18,371
7357,TOYOTA,Tundra 4WD,PICKUP TRUCK - STANDARD,5.7,8,AS6,X,18.0,14.2,16.3,17,381

In [ ]:
# Question 22
# Display all vehicles whose Engine Size(L) is greater than 4.0.
f[f['Engine Size(L)'] > 4.0]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
13,ASTON MARTIN,DB9,MINICOMPACT,5.9,12,A6,Z,18.0,12.6,15.6,18,359
14,ASTON MARTIN,RAPIDE,SUBCOMPACT,5.9,12,A6,Z,18.0,12.6,15.6,18,359
15,ASTON MARTIN,V8 VANTAGE,TWO-SEATER,4.7,8,AM7,Z,17.4,11.3,14.7,19,338
16,ASTON MARTIN,V8 VANTAGE,TWO-SEATER,4.7,8,M6,Z,18.1,12.2,15.4,18,354
17,ASTON MARTIN,V8 VANTAGE S,TWO-SEATER,4.7,8,AM7,Z,17.4,11.3,14.7,19,338
...,...,...,...,...,...,...,...,...,...,...,...,...
7291,ROLLS-ROYCE,Phantom EWB,FULL-SIZE,6.7,12,AS8,Z,20.0,11.8,16.3,17,382
7292,ROLLS-ROYCE,Wraith,MID-SIZE,6.6,12,AS8,Z,19.6,12.8,16.5,17,387
7348,TOYOTA,Sequoia 4WD,SUV - STANDARD,5.7,8,AS6,X,18.5,13.9,16.4,17,385
7356,TOYOTA,Tundra,PICKUP TRUCK - STANDARD,5.7,8,AS6,X,17.7,13.6,15.9,18,371
7357,TOYOTA,Tundra 4WD,PICKUP TRUCK - STANDARD,5.7,8,AS6,X,18.0,14.2,16.3,17,381

In [75]:
# Question 23
# Display only the vehicles manufactured by BMW.
f.query("Make == 'BMW'")

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
76,BMW,320i,COMPACT,2.0,4,A8,Z,10.0,6.5,8.4,34,193
77,BMW,320i,COMPACT,2.0,4,M6,Z,10.4,6.7,8.7,32,200
78,BMW,320i xDRIVE,COMPACT,2.0,4,A8,Z,10.2,7.0,8.8,32,202
79,BMW,328d xDRIVE,COMPACT,2.0,4,A8,D,7.6,5.5,6.7,42,181
80,BMW,328d xDRIVE TOURING,STATION WAGON - SMALL,2.0,4,A8,D,7.6,5.5,6.7,42,181
...,...,...,...,...,...,...,...,...,...,...,...,...
6635,BMW,X7 xDrive40i,SUV - STANDARD,3.0,6,AS8,Z,12.0,9.4,10.8,26,254
6636,BMW,X7 xDrive50i,SUV - STANDARD,4.4,8,AS8,Z,15.5,11.4,13.6,21,318
6637,BMW,X7 M50i,SUV - STANDARD,4.4,8,AS8,Z,15.5,11.4,13.6,21,318
6638,BMW,Z4 sDrive30i,TWO-SEATER,2.0,4,AS8,Z,9.5,7.4,8.5,33,200
6639,BMW,Z4 M40i,TWO-SEATER,3.0,6,AS8,Z,10.3,8.0,9.3,30,216

In [ ]:
# Question 24
# Using query(), display all vehicles having 8 cylinders
f.query("Cylinders == 8")

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
15,ASTON MARTIN,V8 VANTAGE,TWO-SEATER,4.7,8,AM7,Z,17.4,11.3,14.7,19,338
16,ASTON MARTIN,V8 VANTAGE,TWO-SEATER,4.7,8,M6,Z,18.1,12.2,15.4,18,354
17,ASTON MARTIN,V8 VANTAGE S,TWO-SEATER,4.7,8,AM7,Z,17.4,11.3,14.7,19,338
18,ASTON MARTIN,V8 VANTAGE S,TWO-SEATER,4.7,8,M6,Z,18.1,12.2,15.4,18,354
32,AUDI,A8,MID-SIZE,4.0,8,AS8,Z,13.7,8.3,11.3,25,265
...,...,...,...,...,...,...,...,...,...,...,...,...
7281,RAM,1500 Classic,PICKUP TRUCK - STANDARD,5.7,8,A8,X,15.7,11.0,13.6,21,319
7283,RAM,1500 Classic 4X4,PICKUP TRUCK - STANDARD,5.7,8,A8,X,16.2,11.6,14.1,20,330
7348,TOYOTA,Sequoia 4WD,SUV - STANDARD,5.7,8,AS6,X,18.5,13.9,16.4,17,385
7356,TOYOTA,Tundra,PICKUP TRUCK - STANDARD,5.7,8,AS6,X,17.7,13.6,15.9,18,371
7357,TOYOTA,Tundra 4WD,PICKUP TRUCK - STANDARD,5.7,8,AS6,X,18.0,14.2,16.3,17,381

In [86]:
# Question 25
# Display vehicles that have CO₂ emissions greater than 250 and Cylinders equal to 8.
f.query('CO2 Emissions(g/km) > 250' and 'Cylinders == 8')

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
15,ASTON MARTIN,V8 VANTAGE,TWO-SEATER,4.7,8,AM7,Z,17.4,11.3,14.7,19,338
16,ASTON MARTIN,V8 VANTAGE,TWO-SEATER,4.7,8,M6,Z,18.1,12.2,15.4,18,354
17,ASTON MARTIN,V8 VANTAGE S,TWO-SEATER,4.7,8,AM7,Z,17.4,11.3,14.7,19,338
18,ASTON MARTIN,V8 VANTAGE S,TWO-SEATER,4.7,8,M6,Z,18.1,12.2,15.4,18,354
32,AUDI,A8,MID-SIZE,4.0,8,AS8,Z,13.7,8.3,11.3,25,265
...,...,...,...,...,...,...,...,...,...,...,...,...
7281,RAM,1500 Classic,PICKUP TRUCK - STANDARD,5.7,8,A8,X,15.7,11.0,13.6,21,319
7283,RAM,1500 Classic 4X4,PICKUP TRUCK - STANDARD,5.7,8,A8,X,16.2,11.6,14.1,20,330
7348,TOYOTA,Sequoia 4WD,SUV - STANDARD,5.7,8,AS6,X,18.5,13.9,16.4,17,385
7356,TOYOTA,Tundra,PICKUP TRUCK - STANDARD,5.7,8,AS6,X,17.7,13.6,15.9,18,371
7357,TOYOTA,Tundra 4WD,PICKUP TRUCK - STANDARD,5.7,8,AS6,X,18.0,14.2,16.3,17,381

In [88]:
# 6. Simple String Operations
# Question 26
# Display all vehicle models whose Model name starts with the letter C.
f.query("Model.str.startswith('C')")

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
69,BENTLEY,CONTINENTAL GT,SUBCOMPACT,4.0,8,AS8,Z,16.3,9.8,13.4,21,314
70,BENTLEY,CONTINENTAL GT,SUBCOMPACT,6.0,12,AS8,Z,18.8,11.5,15.5,18,356
71,BENTLEY,CONTINENTAL GTC,SUBCOMPACT,4.0,8,AS8,Z,17.4,10.2,14.2,20,332
72,BENTLEY,CONTINENTAL GTC,SUBCOMPACT,6.0,12,AS8,Z,20.0,12.2,16.5,17,380
73,BENTLEY,CONTINENTAL GT SPEED CONVERTIBLE,SUBCOMPACT,6.0,12,AS8,Z,20.0,12.2,16.5,17,380
...,...,...,...,...,...,...,...,...,...,...,...,...
7331,TOYOTA,Corolla XSE,COMPACT,2.0,4,AV10,X,7.7,6.1,7.0,40,164
7332,TOYOTA,Corolla,COMPACT,2.0,4,M6,X,8.2,6.5,7.4,38,173
7333,TOYOTA,Corolla Hatchback,COMPACT,2.0,4,AV10,X,7.5,5.8,6.7,42,158
7334,TOYOTA,Corolla Hatchback,COMPACT,2.0,4,M6,X,8.4,6.3,7.5,38,174
7335,TOYOTA,Corolla Hybrid,COMPACT,1.8,4,AV,X,4.4,4.5,4.5,63,106

In [91]:
# Question 27
# Convert the values in the Make column to uppercase using a Pandas string method and display the result.
f['Make'].str.upper()

0       ACURA
1       ACURA
2       ACURA
3       ACURA
4       ACURA
        ...
7380    VOLVO
7381    VOLVO
7382    VOLVO
7383    VOLVO
7384    VOLVO
Name: Make, Length: 7385, dtype: str

In [94]:
# 7. Creating and Modifying Columns
# Question 28
# Create a new column called Emission Level. Store High when CO2 Emissions(g/km) is greater than 250; otherwise store Normal. Use apply() with a lambda function.
f['Emission level'] = f['CO2 Emissions(g/km)'].apply(lambda x: 'High' if x > 250 else 'Normal')
f['Emission level']

0       Normal
1       Normal
2       Normal
3         High
4       Normal
         ...
7380    Normal
7381    Normal
7382    Normal
7383    Normal
7384    Normal
Name: Emission level, Length: 7385, dtype: str

In [ ]:
# Question 29
# Display the first 10 rows after creating the Emission Level column.
f[:10]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km),Emission level
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196,Normal
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221,Normal
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136,Normal
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255,High
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244,Normal
5,ACURA,RLX,MID-SIZE,3.5,6,AS6,Z,11.9,7.7,10.0,28,230,Normal
6,ACURA,TL,MID-SIZE,3.5,6,AS6,Z,11.8,8.1,10.1,28,232,Normal
7,ACURA,TL AWD,MID-SIZE,3.7,6,AS6,Z,12.8,9.0,11.1,25,255,High
8,ACURA,TL AWD,MID-SIZE,3.7,6,M6,Z,13.4,9.5,11.6,24,267,High
9,ACURA,TSX,COMPACT,2.4,4,AS5,Z,10.6,7.5,9.2,31,212,Normal

In [101]:
    # Question 30
    # Remove the Emission Level column using drop().
f.drop(columns = ["Emission level"])

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
...,...,...,...,...,...,...,...,...,...,...,...,...
7380,VOLVO,XC40 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,10.7,7.7,9.4,30,219
7381,VOLVO,XC60 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7382,VOLVO,XC60 T6 AWD,SUV - SMALL,2.0,4,AS8,Z,11.7,8.6,10.3,27,240
7383,VOLVO,XC90 T5 AWD,SUV - STANDARD,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7384,VOLVO,XC90 T6 AWD,SUV - STANDARD,2.0,4,AS8,Z,12.2,8.7,10.7,26,248

In [ ]:
# Question 31
# Rename the column CO2 Emissions(g/km) to CO2_Emissions.
f.rename(columns={'CO2 Emissions(g/km)': 'CO2_Emissions'}, inplace=True)

print(f.columns)

Index(['Make', 'Model', 'Vehicle Class', 'Engine Size(L)', 'Cylinders',
       'Transmission', 'Fuel Type', 'Fuel Consumption City (L/100 km)',
       'Fuel Consumption Hwy (L/100 km)', 'Fuel Consumption Comb (L/100 km)',
       'Fuel Consumption Comb (mpg)', 'CO2_Emissions', 'Emission level'],
      dtype='str')

In [106]:
# 8. Conversion and Export
# Question 32
# Select and display only the numeric columns from the dataset using select_dtypes().
f.select_dtypes("int")

      Cylinders  Fuel Consumption Comb (mpg)  CO2_Emissions
0             4                           33            196
1             4                           29            221
2             4                           48            136
3             6                           25            255
4             6                           27            244
...         ...                          ...            ...
7380          4                           30            219
7381          4                           29            232
7382          4                           27            240
7383          4                           29            232
7384          4                           26            248

[7385 rows x 3 columns]

In [108]:
# Question 33
# Convert the first 10 rows of the DataFrame into a NumPy array using to_numpy().
f[:10].to_numpy()

array([['ACURA', 'ILX', 'COMPACT', 2.0, 4, 'AS5', 'Z', 9.9, 6.7, 8.5, 33,
        196, 'Normal'],
       ['ACURA', 'ILX', 'COMPACT', 2.4, 4, 'M6', 'Z', 11.2, 7.7, 9.6, 29,
        221, 'Normal'],
       ['ACURA', 'ILX HYBRID', 'COMPACT', 1.5, 4, 'AV7', 'Z', 6.0, 5.8,
        5.9, 48, 136, 'Normal'],
       ['ACURA', 'MDX 4WD', 'SUV - SMALL', 3.5, 6, 'AS6', 'Z', 12.7, 9.1,
        11.1, 25, 255, 'High'],
       ['ACURA', 'RDX AWD', 'SUV - SMALL', 3.5, 6, 'AS6', 'Z', 12.1, 8.7,
        10.6, 27, 244, 'Normal'],
       ['ACURA', 'RLX', 'MID-SIZE', 3.5, 6, 'AS6', 'Z', 11.9, 7.7, 10.0,
        28, 230, 'Normal'],
       ['ACURA', 'TL', 'MID-SIZE', 3.5, 6, 'AS6', 'Z', 11.8, 8.1, 10.1,
        28, 232, 'Normal'],
       ['ACURA', 'TL AWD', 'MID-SIZE', 3.7, 6, 'AS6', 'Z', 12.8, 9.0,
        11.1, 25, 255, 'High'],
       ['ACURA', 'TL AWD', 'MID-SIZE', 3.7, 6, 'M6', 'Z', 13.4, 9.5,
        11.6, 24, 267, 'High'],
       ['ACURA', 'TSX', 'COMPACT', 2.4, 4, 'AS5', 'Z', 10.6, 7.5, 9.2,
        31, 212, 'Normal']], dtype=object)

In [ ]:
# Question 33
# Convert the first 10 rows of the DataFrame into a NumPy array using to_numpy().
f.columns.str.replace(" ", "-")

Index(['Make', 'Model', 'Vehicle-Class', 'Engine-Size(L)', 'Cylinders',
       'Transmission', 'Fuel-Type', 'Fuel-Consumption-City-(L/100-km)',
       'Fuel-Consumption-Hwy-(L/100-km)', 'Fuel-Consumption-Comb-(L/100-km)',
       'Fuel-Consumption-Comb-(mpg)', 'CO2_Emissions', 'Emission-level'],
      dtype='str')

In [110]:
f.to_csv( "CO2_Emissions_Practice_Output.csv")